env:
  global:
    - GH_REF: github.com/FeiXie-Liam/Feixie-Liam.github.io.git

language: node_js
node_js: 8
branches:
  only:
    - gh-src
cache:
  directories:
    - node_modules
before_install:
  - npm install hexo-cli -g
install:
  - npm install
before_script:
  - git config user.name "FeiXie-Liam"
  - git config user.email xiefei0887@163.com
script:
  - hexo cl
  - hexo g
after_success:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${blog}@${GH_REF}" gh-src:master